### PR TITLE
[DDCI-401] - added unpublish dataset

### PR DESCRIPTION
**Pull request by awset**
https://it-partners.atlassian.net/browse/DDCI-401
screencapture-qdes-ckan-29-docker-amazee-io-dataset-dataset-external-publishing-publish-2021-02-17-16_50_03

### CODE REVIEW

**Comment by MarkCalvert** [comment]
@awset Nice work on the published data, the code looks good and is very readable for a complex feature.\
After merging PR https://github.com/salsa-nathan/ckanext-qdes-schema/pull/115 there are now conflicts with this PR. Can you please resolve these issues above?

Also, I noticed a few things with local testing of this PR:
- There is currently no user access checks for the publish tab, validation, publishing/unpublishing etc. Shouldn't we be checking if the user has 'package_update' access to the dataset?
- I tried publishing to Data.QLD, the publish activity table on screen has a status of 'pending', the ckan-job-worker completed the job successfully, but when I check the 'publish_log' table the status is 'failed' with a validation error message, should this be displayed in the activity table?

**Comment by awset** [comment]
@MarkCalvert with "pending" you need to refresh the browser. auto refresh or auto update the status maybe be good to have but this particular story has no time left, and this "pending" was amendment to previous AC, I guess better to wait until QA.

I added the check_access, thanks.

image

**Comment by MarkCalvert** [comment]
Hi @awang,
The publish activity table is not a refresh issue, looking at the helper `get_publish_activities` I can see it is only retrieving the most recent log and is not looping through all the logs for that resource. Am I missing some logic here or is there some code which is not committed into this PR branch?

**Comment by MarkCalvert** [comment]
Hi @awset,
Because this PR is blocking quite a few other stories from getting deployed in QA I am going to approve and merge this so I can deploy all the publishing stories to QA for testing.
You can create another PR to address the publish activity issue or let it be picked up in QA testing.

**Comment by MarkCalvert** [comment]
Sorry @awset I ignore above, I misunderstood the logic and was assuming the publish activity table would show all publishing activities for a resource, but it seems the business case is to only show the most recent activity. 
Every looks good 😊

**Pull request merged**
